name: "Client Build"
on:
  push:
    branches:
      - "main"
  
  pull_request:
    branches:
      - "main"

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: FakedCubes

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/${EXPORT_NAME}_Windows.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/${EXPORT_NAME}_Linux.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: build/linux